remove non-integer magic numbers for command and data type
The '..._LAST' values in dials/Comms_Hub_Server.py will cause issues with https://github.com/feeph/VU-Server/blob/ee237b6d6842b43d927727743737e846b1415b53/dial_driver.py#L31
because the function assumes `cmd` and `dataType` contain numerical values.
There's no logic in place to handle non-integer values:

```
if dataLen == 0:
    payload = ">{:02X}{:02X}{:04X}".format(cmd, dataType, dataLen)
elif dataLen == 1:
    if data < 256:
        payload = ">{:02X}{:02X}{:04X}{:02X}".format(cmd, dataType, dataLen, data)
    elif data >= 256:
        payload = ">{:02X}{:02X}{:04X}{:04X}".format(cmd, dataType, dataLen+1, data)
    elif dataLen > 1:
        [...]
        payload = ">{:02X}{:02X}{:04X}{}".format(cmd, dataType, int(len(formattedData)/2), formattedData)
```

If `cmd` or `dataType` is 'None' a TypeError is raised:

```
TypeError: unsupported format string passed to NoneType.__format__
```

The 2 values in dials/Comms_Hub_Gauge.py have been removed as well. It does
not look like anything uses this file.

There's a comment that these files were autogenerated by `generate_pyton_classes.py`.
If the files should be left unchanged it is recommended to modify the
function 'dial_driver._sendCommand()' to properly handle cases where `cmd`
and/or `dataTyp` are 'None'.